name: Ruby build 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile: [ Gemfile ]
        ruby-version: ['3.1', '3.2']
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
      CONTINUOUS_INTEGRATION: true
      PROCESS_TIMEOUT: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rails test
      - run: bundle exec rails test:system
      - run: bundle exec rubocop -f github
